### ISSUE TITLE
Blockify the Order Confirmation Template

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#10021]
This epic tracks the conversion of the order confirmation template from a legacy block, to individual inner blocks.
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10025
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10057
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10058
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10053
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10054
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10052
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10051
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10050
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10048
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10049
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10055
```

**Comment by tomxygen** [comment]
I'd love to have a map block that takes the shipping information and displays them onto Google maps.
This is a tutorial on how to make it using Elementor -> https://ecommercehints.com/woocommerce-thank-you-page-map-showing-customer-address
It would be great to be able to create is using blocks.
