### ISSUE TITLE
Order Confirmation Blocks: Shipping (Inner Blocks)

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#10053]
The shipping section is currently made up of a heading block, and a shipping address block:

![Screenshot 2023-06-30 at 15 08 38](https://github.com/woocommerce/woocommerce-blocks/assets/90977/b6cdfb09-9ecd-4fbf-8f6b-e8af39af2108)

However, there is a problem because shipping address may be displayed conditionally e.g. if an order has no shipping address, this section should be hidden. This would result in the heading being displayed, but no address below it.

To fix this we need to create a wrapper called "Order Confirmation Shipping". This should contain inner blocks (the heading, and the shipping address block). The wrapper can then be used to hide all of the contents if shipping is not needed.

#### Tasks

- [ ] Create shipping block to act as a wrapper for inner blocks
- [ ] Include heading and shipping address inner block as standard. These should be locked.
- [ ] Ensure shipping address inner block has correct name, description, and an icon

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce-blocks/issues/10094

**Comment by tomxygen** [comment]
it would be great if, based on that address, there was a google maps that shows the customer his own address.

**Comment by mikejolley** [comment]
@tomxygen Inner blocks opens the possibility for this, but in the first iteration we won't be deviating from the current design.
