### ISSUE TITLE
Order Confirmation Blocks: Billing Address (Inner Blocks)

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#10054]
## Objectif

We want to complete the Billing address implementation for the editor side. The heading block isn't included in this ticket.

<img width="536" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/acae2ba8-35c0-4295-b82d-d322ab413f26">

## Tasks

- [ ] Add any missing block placeholders
- [ ] Add Block title that will be displayed in `Settings -> Template`
- [ ] Add Block description that will be displayed in `Settings -> Template`
- [ ] Add Block icon that will be displayed in `Settings -> Template`

## Screenshots

<img width="298" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/134059b3-7d5f-4faf-8360-74cd97bc1e97">

_Block info in the inspetor_

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce-blocks/issues/10094

**Comment by tarhi-saad** [comment]
I Updated the PR description to include only the requirement for the Billing Inner Block (the heading is excluded). @mikejolley, do you think this is an accurate description?
