### ISSUE TITLE
Store Customization MVP (Phase 1)

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10087]
Build a brand new Store Customization experience to give merchants an innovative, no-code way to select and customize a theme for their new store.

Ref. Project Kickoff: pdnLyh-3Rq-p2
Ref. SE project thread: pdnLyh-3Tv-p2
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10086
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10208
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10209
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10210
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10211
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10212
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10214
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10215
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10216
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10217
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10218
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10273
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10290
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10293
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10322
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10304
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10324
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10347
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10376
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10458
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10478
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10519
```

**Comment by nefeline** [comment]
I'm going ahead and closing out this epic as Phase 1 for this project is now complete. Please refer to https://github.com/woocommerce/woocommerce-blocks/issues/10568 for work related to Phase 2.
