### ISSUE TITLE
Product Collection - PHP Unit Tests

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#10176]
This issue covers the necessary development and implementation of Unit Tests PHP Utilities for our new block, the "Product Collection"

As a codebase is partially the same as for Products (Beta) block, the test should be reused whenever possible.

Scenarios to be provided.
```[tasklist]
### Tasks
- [x] Test merging on sale queries.
- [x] Test merging stock status queries.
- [x] Test merging default stock queries that should use product visibility queries instead of meta query for stock status.
- [x] Test merging attribute queries.
- [x] Test merging order by rating queries.
- [x] Test merging order by popularity queries.
- [x] Test if the product visibility query exists in the merged query.
- [x] Test merging multiple queries.
- [x] Test merging filter by max price queries.
- [x] Test merging filter by min price queries.
- [x] Test merging filter by min and max price queries.
- [x] Test merging filter by stock status queries.
- [x] Test merging filter by attribute queries.
- [x] Test updating REST query without attributes.
- [x] Test updating REST query with attributes.
- [x] Test merging taxonomies
```
