### ISSUE TITLE
Store Customization > Design feedback on wireframed and new patterns

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10458]
This is an issue for us to capture any feedback from the design team for the wireframed and new patterns in the Store Customization MVP project https://github.com/woocommerce/woocommerce-blocks/issues/10087
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10637
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10598
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10667
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10478
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10613
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10519
```

**Comment by jarekmorawski** [comment]
Regarding left and right paddings, I experimented with a few different options. I went with 64 px on desktop and 32 px on mobile. However, I think they should always follow whatever is set under Global Styles > Layout.

<img width="321" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/79307566/df930312-f3bf-4a4f-af42-32f77a21ee49">

For WooX starting templates, we'd default to 64/32 px and let the user change it in the site editor later. All patterns should automatically adjust and scale. Is that feasible?

**Comment by nefeline** [comment]
Hi there @jarekmorawski ! Taking the Testimonials Single Pattern as an example https://github.com/woocommerce/woocommerce-blocks/pull/10600 , regarding:

> I think they should always follow whatever is set under Global Styles > Layout.

I've changed the layout type for the column with the content to constrained, so the inner block now uses the content width and can be inherited.

> I went with 64 px on desktop and 32 px on mobile.

> For WooX starting templates, we'd default to 64/32 px

Unfortunately, setting different paddings for mobile x desktop view is not possible, so I kept it as 32px across the board: let me know if that works!

**Comment by nefeline** [comment]
We have finished addressing all design feedback, so I'm going ahead and closing out this issue 👍 .
