### ISSUE TITLE
Store Customization MVP (Phase 2)

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10568]
Following up on the work made on the initial phase of this project on https://github.com/woocommerce/woocommerce-blocks/issues/10087, the goal of phase two is to have the images for patterns populated with Verticals (which is an API built to help designers and developers choose vertical-specific images for use in templates and automatically generated content). The displayed images should dynamically change depending on what the user decides to add as a description for their business on their AI settings screen.

## Scope

All the details of the planned technical implementation are described on https://github.com/woocommerce/woocommerce-blocks/issues/10503
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10503
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10609
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10615
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10699
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10617
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10618
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10620
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10623
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10658
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10659
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11080
```
