### ISSUE TITLE
Update data stores documentation

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10994]
At present, the [data stores README.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/README.md) includes documentation for only these data stores:

- [collections](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/collections/README.md)
- [query-state](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/query-state/README.md)
- [schema](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/schema/README.md)

However, the following data stores are not covered:

- cart
- checkout
- payment
- store-notices
- validation

Additionally, these undocumented data stores lack a README.md file in their respective root directories.

Lastly, it would be beneficial to add a link to the [data stores README.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/README.md) in the [WooCommerce Blocks Handbook](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/README.md) to enhance the discoverability of the data store documentation.

```[tasklist]
### Tasks
- [ ] Document **cart** in https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/README.md
- [ ] Document **checkout** in https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/README.md
- [ ] Document **payment** in https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/README.md
- [ ] Document **store-notices** in https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/README.md
- [ ] Document **validation** in https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/README.md
- [ ] Create https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/cart/README.md
- [ ] Create https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/checkout/README.md
- [ ] Create https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/payment/README.md
- [ ] Create https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/store-notices/README.md
- [ ] Create https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/validation/README.md
- [ ] Link to [data stores README.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/README.md) from [WooCommerce Blocks Handbook](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/README.md)
```

**Comment by hritikchaudhary** [comment]
Hi @nielslange Can I work on it?

**Comment by nielslange** [comment]
> Hi @nielslange Can I work on it?

Sure, @hritikchaudhary. Thanks for volunteering to work on this issue. I've just assigned it to you. If you have any questions or need assistance, please don't hesitate to reach out. 🙌

**Comment by nielslange** [comment]
Closing this issue due to #11336.
