### ISSUE TITLE
Interactivity API: implement the new `store()` API

### ISSUE THREAD

**Issue by DAreRodz** [woocommerce/woocommerce-gutenberg-products-block#11065]
This tracking issue lists all the requirements to implement the new `store()` API, which is the Interactivity API's state manager.

The whole API proposal is extensively detailed in https://github.com/WordPress/gutenberg/discussions/53586, and the idea is to first develop `store()` here in WooCommerce Blocks and, once most of the API is tested and functioning, move all the code to Gutenberg and add proper, automated testing, documentation, etc.

This feature is being implemented in the following PR:

- https://github.com/woocommerce/woocommerce-blocks/pull/11071

You can check an example of the Product Button using it in the following branch:
- [`interactivity-api-refactor-product-button-with-new-store-api`](https://github.com/woocommerce/woocommerce-blocks/compare/interactivity-api-new-store-api...interactivity-api-refactor-product-button-with-new-store-api)

## Tasks

- [x]  The default namespace is stored in `data-wp-interactive`
- [x]  The namespace is passed as a string during store creation
- [x]  Stores return stable references to their properties
- [x]  External stores can be accessed using the same API
- [x]  Multiple parts of the same store can be defined in different files
- [x]  Objects returned by `store()` are typed
- [x]  External consumers can import a typed store
- [x]  Contextual values like `context` or `ref` should be accessed inside the functions
- [x]  Actions are just regular JavaScript functions
- [x]  Derived state (selectors) can use getters
- [x]  Derived state (selectors) can be moved back to state
- [x]  Defining the initial state in the server
- [x]  Types from the initial server state
- [x]  Accessing other namespaces in the directives
- [x]  Creating and accessing context from other namespaces in the directives
- [x]  Accessing context from other namespaces in the store
- [x]  Typing contexts
- [x]  Async Actions should use generators instead of async/await
- [x]  Stores should be able to import logic dynamically
- [x]  Stores should be able to build façades of their public APIs
- [x]  Stores should be able to define getters and functions anywhere (not only in `state` or `actions`)
- [x]  Element-related APIs (`getElement()`) https://github.com/WordPress/gutenberg/discussions/53586#discussioncomment-7166772
- [x]  Private stores https://github.com/WordPress/gutenberg/discussions/51596#discussioncomment-7198628
- [x] Deep merge the raw stores instead of the proxies

## Migration

- [x] Product Button and Product Collection blocks
  - https://github.com/woocommerce/woocommerce-blocks/pull/11558
- [x] Product Gallery block
  - https://github.com/woocommerce/woocommerce-blocks/pull/11721

**Comment by luisherranz** [comment]
> Derived state (selectors) can be moved back to state

We need to think about this one. As of now, my only idea is to make the usage `computed` in getters optional in `deepsignal` using an `options` import similar to Preact's:

```js
import { options } from "deepsignal";

options.computedGetters = false;
```

It's kind of a shame because when the value doesn't depend on the scope (context, element state, element ref), the `computed`'s are fine.

**Comment by luisherranz** [comment]
As we're going to be proxying state anyway, maybe we could detect getters on our side and if they are run inside of a scope, move them to a map and wrap them with computeds ourselves. I'll try that in the next days 🙂

**Comment by luisherranz** [comment]
> maybe we could detect getters on our side and if they are run inside of a scope, move them to a map and wrap them with computeds ourselves

It worked fine. I commented on the PR:

- https://github.com/woocommerce/woocommerce-blocks/pull/11071#issuecomment-1746426671

**Comment by luisherranz** [comment]
Now that this is completed, we've added a list of tasks for the next steps to the Gutenberg's Tracking Issue:

- https://github.com/WordPress/gutenberg/issues/53740

We can keep using this Tracking Issue to keep track of the individual tasks that we need to accomplish in Woo, like the migration of the different blocks.

Our next step is to open a PR with the new `store()` API in Gutenberg to make sure that the e2e tests that we have in Gutenberg pass.

**Comment by luisherranz** [comment]
Okay, now that that is completed, the next task is to migrate all the existing blocks:

- Product Button block
- Products Collection block
- Product Gallery block

@darerodz and I will take care of the Product Button and Products Collection blocks, and we'll help the Woo team with the rest of the blocks.

Once we've merged the `interactivity-api-new-store-api` branch in `trunk`, we will start migrating the blocks that are still in progress:

- Filter blocks

---

@sunyatasattva could you please take a look and update the list of blocks if necessary?

**Comment by DAreRodz** [comment]
All the migration work is done (only awaiting approval in https://github.com/woocommerce/woocommerce-blocks/pull/11071 and e2e tests to be fixed).

As a wrap-up, I'll summarize the tasks for subsequent PRs and all the notes left in the comments―all related to the Interactivity API runtime.

### Tasks
- [ ] Uncomment `prefetch` in the `navigation-link` directive. ([link](https://github.com/woocommerce/woocommerce-blocks/pull/11071/files/5d91a56a0d4134258407f14946688e35f2f1f2b6#r1395681340))
- [ ] Use TSDocs to document the new APIs. ([link](https://github.com/woocommerce/woocommerce-blocks/pull/11071/files/5d91a56a0d4134258407f14946688e35f2f1f2b6#r1356989089))
- [ ] Add `elementState` to the `resolve` scope. ([link](https://github.com/woocommerce/woocommerce-blocks/pull/11071/files/5d91a56a0d4134258407f14946688e35f2f1f2b6#r1375857952))

### Notes
- We must wrap error logs with `if (SCRIPT_DEBUG)` blocks in Gutenberg. ([link](https://github.com/woocommerce/woocommerce-blocks/pull/11071/files/5d91a56a0d4134258407f14946688e35f2f1f2b6#r1357000023), [link](https://github.com/woocommerce/woocommerce-blocks/pull/11071/files#r1357010899))
- We could consider removing the deep immutable logic from the `getElement()` production version. ([link](https://github.com/woocommerce/woocommerce-blocks/pull/11071/files/5d91a56a0d4134258407f14946688e35f2f1f2b6#r1356993268))
- An API to access "computed"s would be required for future `wp-text` and `wp-bind` optimizations. ([link](https://github.com/woocommerce/woocommerce-blocks/pull/11071/files/0601c4eca294edac54da3b551d2b16fcae8ce74d#r1348915265))
- We could (unlikely) face the case where a getter might run outside of scope and still need access to the default namespace. ([link](https://github.com/woocommerce/woocommerce-blocks/pull/11071/files/0601c4eca294edac54da3b551d2b16fcae8ce74d#r1348909250))

cc: @luisherranz
