### ISSUE TITLE
Epic: Enabling Cart, Checkout, and Order Confirmation Blocks as Default for New Stores

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#11264]
The primary goal of this epic is to enable the Cart, Checkout, and Order Confirmation blocks as the default experience for new stores running WC 8.3+ (released on Nov 14th). 

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11266
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11267
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11269
```

**Comment by wavvves** [comment]
Closing this as changes will live in Core.

Related Blocks PR https://github.com/woocommerce/woocommerce-blocks/pull/11372
