### ISSUE TITLE
Follow up: Filter blocks and All Products block should update and retrieve values from the query string

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#1126]
All types of filter blocks should add and read values from the query string. This includes the attribute filter, and the price filter.

When filtering, the query string parameters should be added.

On page load, the query string parameters should be read and applied.

## Tasks:

* [ ] create new hook for managing query string
* [ ] Convert existing All Products block usage of `withQueryString` to the new hook.
* [ ] Implement and wire up query string behaviour for filter blocks.
