### ISSUE TITLE
Moving WooCommerce Blocks components into the checkout package

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#11661]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11353
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11223
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11662
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11654
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11312
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11456
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11465
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11524
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11657
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11622
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11489
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11618
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11636
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11635
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11469
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11481
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11682
```
