### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#11678]
This is a tracking issue to fix PHP 8.1 compatibility issues reported by Rector.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11667
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/11658
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/11668
```
