### ISSUE TITLE
Cart block

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#1289]
### User Story
As a merchant
I want a block that allows adding an optimized cart layout
So I can improve my cart conversion rate and quickly change some of the cart settings

### Acceptance Criteria

**Restrictions**
 - [x] ~~The block is only available in the Cart page~~ (see #1305) Won't be part of the block for first release because cart block can run alongside woo default cart if desired.

**Tooltip**
 - [ ] When the user selects the block in the block picker he should see a notification drawing his attention to the block settings (see #1469)

**Full/Empty cart selection**
 - [x] The user can see the full cart and the empty cart layout and switch between the two layouts

**Displaying products** (see #1487)
 - [x] ~~The full cart it's displayed with an existing product~~ We are using sample data.
 - [x] If the user doesn't have a product in the store he should see the full cart with a sample product

**Shipping** (see #1488)
 - [x] The user can show/hide the shipping calculator (setting currently available on WooCommerce > Settings > Shipping > Shipping options). The shipping calculator should be on by default
 - [x] The user can choose to hide shipping costs until an address is entered (setting currently available on WooCommerce > Settings > Shipping > Shipping options). This option should be off by default
 - [x] ~Any change to those settings in the block editor should be reflected on the same setting on WooCommerce > Settings > Shipping > Shipping options~ We're not going to implement this as per [this comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1488) (and confirmed in a slack discussion with @garymurray).
 - [x] ~Both shipping settings should be off by default if the user doesn't have any physical products in the store~ See discussion in 1488 - options will _not_ be hidden from user but only apply when there are shippable products in the cart.

**Coupon** (see #1411)
- [x] If the user has the coupons' usage disabled on WC Settings we hide it in the cart layout (both on the block editor and in the front-end)
 - [x] The user can show/hide the coupon code field. The coupon field should be on by default (it can be backlogged if we don't have enough time)

**Feedback**
 - [x] The user can give feedback about the block by clicking in the "Give feedback" section. We can link this to the ideas board: https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=384565

**Payments badges**
 - [x] The accepted payment badges will change depending on the payment gateways available in the store (we only support Paypal and Stripe in v1) (see #1472)

**Empty cart editing (it can be backlogged if we don't have enough time during this cycle)**
 - [x] In the empty cart the user can show/hide the icon and change its size
 - [x] In the empty cart the user can edit the header text
 - [x] In the empty cart the user can edit the "continue shopping" text and link
 - [x] In the empty cart the user can the new products block

**Front-end behavior** (see #1489)
 - [x] The cart will be automatically updated when a shopper removes an item from the cart
 - [x] The cart will be automatically updated when a shopper updates an item quantity
 - [x] The shopper can see how many products are in stock when there are 3 products or less in stock (scarcity label)
 - [x] The cart will be automatically updated when a shopper changes the shipping option
 - [x] The shopper can change the shipping address in the cart
 - [x] The cart will be updated when the shopper changes the shipping address
 - [x] The shopper can add a coupon code in the cart
 - [x] The cart will be updated when the shopper adds a valid coupon code
 - [x] The cart layout is responsive and it should be adapted to the screen width/height

**Links**
MT: p6q8Tx-137-p2
[Final desktop mockup](https://www.figma.com/file/n90hX6hG3wwQbYwsYsrJnj/Gutenberg-based-cart-%26-checkout?node-id=743%3A33222)
[Final mobile mockup](https://www.figma.com/file/n90hX6hG3wwQbYwsYsrJnj/Gutenberg-based-cart-and-checkout?node-id=744%3A2980)

Validation Error Indicators for fields: [figma](https://www.figma.com/file/Pfw5Qa1UOw03RiJere3Wlo/Automattic-Components?node-id=4117%3A16532)

#### Sample mockups 

(see figma designs above for details)

Cart block (with items) in editor context (on desktop).
<img width="1263" alt="Screen Shot 2020-01-08 at 8 33 28 AM" src="https://user-images.githubusercontent.com/4167300/71923308-a4346d00-31f1-11ea-8d49-ba94d19c791a.png">

Cart with items on mobile.
<img width="428" alt="Screen Shot 2020-01-08 at 8 32 37 AM" src="https://user-images.githubusercontent.com/4167300/71923313-a72f5d80-31f1-11ea-9c08-17d2846b1046.png">

**Comment by senadir** [comment]
I did a quick spin of the design I have a single note about "Shipping Costs", it seems a bit ambiguous, enabling it hides shipping costs, I think we should reconsider the help text or the label since they contradict. cc @garymurray

**Comment by nerrad** [comment]
You'll note that as of this post there are a number of items _not_ checked off.  This is because the user stories required a lot of supporting work as a part of completing them.  I've gone through and linked to issues that will:

* Ensure the user story is completed (there may be pulls in progress or done that have been completed, if that's the case the issue will be closed)
* Can be used to track what is left to do (and includes the estimate in our release chart planning).
* Can be used to identify what we might want to tweak/modify for the initial iteration if we need to reduce scope to meet our cycle targets.

**Comment by garymurray** [comment]
> I did a quick spin of the design I have a single note about "Shipping Costs", it seems a bit ambiguous, enabling it hides shipping costs, I think we should reconsider the help text or the label since they contradict. cc @garymurray

@senadir does this resolve what you found here:

<img width="369" alt="Screenshot 2020-01-13 at 11 22 28" src="https://user-images.githubusercontent.com/10805911/72252350-0c6ebe80-35f7-11ea-9f26-e3d698f97ea3.png">

**Comment by nerrad** [comment]
The release of `2.6.0` fulfills the purpose of this epic.
