### ISSUE TITLE
REST API: Cart and Checkout Block Requirements

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#1312]
In order for the cart and checkout blocks to become functional, a series of APIs will be required to interact with the server and WooCommerce data. 

Many of these APIs do not exist, and current code in core is not flexible enough to handle these scenarios due to it being tightly coupled to the existing cart and checkout.

The following APIs will be added to the **Store API** in the blocks plugin. APIs will require customer context, so like the current cart API, this will use the current logged in user, or customer session cookie for guests.

*Unanswered Questions/Notes:*
1. Do we need an API to get checkout fields, or do we handle that client side? Core handles "locales" based on selected country where labels and field positions are updated. For example, renaming state -> county, or hiding certain non-applicable fields.
2. Newsletter signup is included in the mocks but it's not clear how that data will be used. We could store it to customer meta using the customer API and allow plugins to read it in a standardized way?
3. We need to explore what totals are needed in the cart, looking to core and the mockups. For example, subtotal, taxes, discount total etc.

**TODO**
~~- **Payment Methods API** - Lists available/registered payment methods. Used by the cart to show a payment methods list (icons only), and used by the checkout to show available express and regular payment methods. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1321~~
- [x] **Order API** - We need to allow the new checkout block to create orders in WooCommerce.  See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1322
- [x] **Customer API** - Stores and retrieves location and address session data for the **current** customer. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1320
- [x] **Cart Coupons API** - List, remove, and apply coupons. This API will not hold data "about" coupons, just track what is applied and what benefit it granted. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1323
- [x] **Products API** - Cart and order summaries show remaining stock (if low in stock) so we need additional data added to this endpoint. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1319
- [x] **Cart Totals** - The current cart API includes a total, but we need more detailed totals for the cart totals display during cart, and order summary display during checkout. #1324
- [x] **Shipping Rates API** - Returns shipping rates for carts. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1318

**Comment by nerrad** [comment]
I'll give some more fuller feedback at some future point but initially thought I'd ask, is there any prior art that we can learn/draw from as we deliberate this?  Any work that Wp.com has done or other ecommerce applications?

**Comment by haszari** [comment]
Lots more exploration to do on all these endpoints, as you say @mikejolley each endpoint is a significant chunk of work. 

The only feedback I have right now is the low-stock API, I'm thinking this should probably return a boolean based on the threshold, rather than raw stock numbers. Stock quantity is not actually needed, and we're replicating server logic – probably safest to keep this API focused on the essential need. Another option would be to include the `low_stock` attribute in a different API response, e.g. cart state (rather than its own api).

**Comment by haszari** [comment]
Let's discuss the APIs needed for the Cart block in #1213 .

**Comment by mikejolley** [comment]
@nerrad This is a good prior art for shipping rates: https://help.shopify.com/en/themes/development/getting-started/using-ajax-api cc @haszari 

So assuming we used the in-session cart, we'd just send the customer address and get back rates. `/cart/shipping-rates` makes sense.

> Any work that WP.com has done or other ecommerce applications?

Not familiar with their APIs but looking at docs it doesn't seem to cover eCommerce usage.

**Comment by mikejolley** [comment]
Shipping rates: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1318

**Comment by nerrad** [comment]
@woocommerce/blocks @mikejolley has agreed to take point on this epic but he is still going to need help.  If you are willing to help him get this epic done please assign yourself to the epic (it's okay to have multiple peeps on it).  That helps Mike know who he can ping too if necessary.

**Comment by haszari** [comment]
Added an issue for cart totals: #1324
