### ISSUE TITLE
Create CountyInput component

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1575]
Part of #1348.

We need an input field that allows introducing a county/state.

### Breakdown
When implementing these, take a look at #1574 since some of these tasks might be shared or are very similar.
* [x] Create initial component (#1727).
* [x] Load counties with AssetDataRegistry (#1727).
* [ ] Switch from `CustomSelect` to `ComboboxControl` (issue: #1752).
* [ ] Make sure the correct wording (_County_, _State_, _Province_) is used for each country, see [`get_country_locale()`](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Countries.html#730-1265) (issue: #1730).

**Comment by Aljullu** [comment]
I created follow-ups for the remaining tasks of this issue, so closing this one.
