### ISSUE TITLE
Move base/components into subfolders if they are only relevant to one specific block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1962]
Initially discussed in #1949.

In `base/components` we have several components which are only relevant to specific blocks, so we would like to move them into subfolders to make that clearer.

Some suggestions:
* [x] `address-form`, `shipping-calculator`, `shipping-location`, `shipping-rates-control` and `totals` could go under `cart-checkout` (#2034).
* [x] `checkout` subfolder and `cart-checkout` could be merged (#2034).
* [x] `review-list`, `review-list-item` and `review-sort-select` could go under `reviews` (#2034).
* [ ] `filter-submit-button`, `product-list`, `product-list-item`, `product-sort-select` could go under `all-products-and-filters` (I'm not 100% sure about this one, it seems a bit too broad and it doesn't match a folder under `blocks`).
* [ ] `payment-methods` should go under `cart-checkout`.

**Comment by ralucaStan** [comment]
@Aljullu regarding the `all-products-and-filters` suggestion, I agree it seems too broad.

I identified these dependencies: 

- filter-submit-button -> attribute filter & price filter (so I suggest not to move it)
- product-list -> all products
- product-list-item -> product-list
- product-sort-select -> product-list

I would group the product list related components:
- weather we move `product-sort-select` and `product-list-item` under `product-list` and keep them in base components
- or we move all `product-list,-list-item,-sort-select` under `all products` in block, but I did not see this as a pattern.

What do you think? Should we also bring this up with the team, component structure is always an issue?

**Comment by Aljullu** [comment]
I would lean towards this option:

> weather we move `product-sort-select` and `product-list-item` under `product-list` and keep them in base components

In the future, some PHP-based product grid blocks might end up being refactored to use the same components as All Products, so a `product-list` folder which is generic for all blocks that display products sounds better than having a different folder for each block.

**Comment by ralucaStan** [comment]
Ok, this option made more sense for me as well. I will create a PR for it.
