### ISSUE TITLE
Cover basic block creation for all of our blocks in E2E.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2395]
As we decided to do a biweekly release, we will be shipping more code more frequently, previously we tested all of legacy and old block catalog manually, across WordPress versions, this is a tedious and lengthy process, we should aim to extend our current basic E2E tests (create and save a block) to all of our blocks (old and new).

#### Blocks that already have tests
- [x] woocommerce/all-products - test already in main
- [x] woocommerce/single-product - test already in main, block is still in development
- [x] woocommerce/checkout - test already in main
- [x] woocommerce/cart - test already in main
- [x] woocommerce/product-search - test already in main

🙌 @senadir for getting these up and running and working reliably in Travis against multiple versions of WordPress!

#### Reviews blocks
- [x] woocommerce/all-reviews - ~~WIP on #2756~~ now in #2799 @haszari 
- [x] woocommerce/reviews-by-product @mikejolley 
- [x] woocommerce/reviews-by-category @mikejolley 

#### `All Products` filter blocks
- [ ] woocommerce/price-filter - WIP on #2756 
- [ ] woocommerce/attribute-filter - WIP on #2756 
- [ ] woocommerce/active-filters - WIP on #2756 

#### Product grid blocks (legacy/server-side-render) https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4566
- [ ] woocommerce/featured-category
- [ ] woocommerce/featured-product
- [ ] woocommerce/handpicked-products
- [ ] woocommerce/product-best-sellers
- [ ] woocommerce/product-categories
- [x] woocommerce/product-category
- [ ] woocommerce/product-new
- [x] woocommerce/product-on-sale
- [x] woocommerce/products-by-attribute
- [ ] woocommerce/product-top-rated

**Comment by haszari** [comment]
I see there is a bunch of progress toward this in #2756 🎉

I'm going to grab this issue and that PR. Here's my plan:

- Find out where we're at - what block create tests are already running successfully on master.
- Map out the remaining blocks we need to test (maybe categorised into related chunks) - will add a checklist to this issue.
- Add new tests in new PRs (will borrow heavily from #2756) and keep this issue updated with progress.

**Comment by senadir** [comment]
This was never fully done, but I still hope we can revisit this in the future.

**Comment by Aljullu** [comment]
@senadir @nielslange is this issue the same as https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4643? Wondering if this one can be closed or there is anything else that needs to be done.

**Comment by senadir** [comment]
Yes, this can be closed!
