### ISSUE TITLE
[Single Product Block] Update CSS Styles and create shared product styles

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2527]
The single product block will need proper styling, and in addition, some styles will need to become shared. e.g. All Products block styles will be similar to some parts of the single product block.

**Todos:**
- [x] Create common styles between all products and single products blocks covering atomic components
- [x] Create styles for single products specifically
- [x] Check theme compatibility
