### ISSUE TITLE
Implement new Cart and Checkout designs to improve theme compatibility

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2605]
This was requested as an idea in:
https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/40549039-allow-for-themes-colour-scheme-to-be-used-in-the-b

We want to update the _Cart_ and _Checkout_ blocks so they play better with themes. Currently, most of their colors are hardcoded, but we would like to use the ones that we inherit from the theme. These are example designs from @LevinMedia:

### Light theme
| Cart | Checkout |
| --- | --- |
| ![imatge](https://user-images.githubusercontent.com/3616980/83533985-8f35de80-a4f0-11ea-9081-1a54dec93c4e.png) | ![imatge](https://user-images.githubusercontent.com/3616980/83534062-a7a5f900-a4f0-11ea-88f6-0439fbbd2b6b.png) |

### Dark theme
| Cart | Checkout |
| --- | --- |
| ![imatge](https://user-images.githubusercontent.com/3616980/83534120-bab8c900-a4f0-11ea-9abb-8e0c4583c1e7.png) | ![imatge](https://user-images.githubusercontent.com/3616980/83534129-c0161380-a4f0-11ea-985f-851b40d2e92b.png) |

## Issues & PRs
* [x] Cart & Checkout: update item count badge so it works in light and dark backgrounds #2617 
* [x] Update Cart & Checkout heading styles #2597
* [x] Replace all hardcoded font-color declarations with alternatives #2459 
* [x] Checkout: update progress indicator design #2618
* [x] Cart & Checkout: style button depending on theme colors #2761 & https://github.com/woocommerce/storefront/pull/1412

**Comment by Aljullu** [comment]
Closing this issue since all its dependencies have been already merged.
