### ISSUE TITLE
Verify/Test WooCommerce Blocks functionality with WordPress 5.6

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3319]
This is intended as a tracking issue for ensuring we test all WooCommerce blocks for Compatibility with WordPress 5.6.

For each block, smoke test block works correctly in editor and front end, for example:

- Editor - choosing all various inspector controls and make sure they work.
- Editor - as you are doing the above watch for console errors/warnings.
- Frontend - verifying blocks load and have the expected functionality.
- Frontend - while testing the above watch for console errors/warnings.

#### Block checklist
@woocommerce/rubik When you test a block tick it off, and add info about environment (e.g. exact WordPress version, Blocks version etc). If you find a bug, log it!

- [x] Featured Category
- [x] Best Selling Products
- [x] Top Rated Products
- [x] On Sale Products
- [x] All Reviews
- [x] Featured Product
- [x] Hand-picked Products
- [x] Product Categories List
- [x] Products by Category
- [x] Newest Products
- [x] Products by Attribute
- [x] Reviews by Product
- [x] Reviews by Category
- [x] Product Search
- [x] Products by Tag
- [x] All Products & filters
   - [x] Filter by price
   - [x] Filter by attribute
   - [x] Active filters
- [x] Cart
- [x] Checkout

**Comment by haszari** [comment]
My test setup:

- [Jurassic.Ninja site](https://neutral-echidna.jurassic.ninja)
- WordPress `5.6-RC1` via wp-cli `wp core update --version=5.6-RC1`
- WooCommerce `4.8.0-beta.1` via WooCommerce Beta Tester plugin
- Storefront `2.9.0` latest release
- WooCommerce Blocks `3.8.0` latest release
- Mostly testing in Safari

Tested these blocks and found no blockers, found one deprecation issue.

- `Best Selling Products`
- `On Sale Products`
- `Top Rated Products`
- `Featured Category` #3438

**Comment by nerrad** [comment]
Just a note for reference as we go through this regarding any deprecated notices. If resolving the deprecation requires WordPress 5.6, let's still create the issue, but it will likely end up in our backlog because we can't really address it in most cases until we are able to bump minimum required WP version to 5.6.

**Comment by haszari** [comment]
Tested these guys, same setup as above. Logged a few more deprecation warnings in #3438.

- `Hand-picked Products`
- `Product Categories List`
- `All Reviews`
- `Featured Product`

Note I saw an issue with the focal point picker in `Featured Product` - snapped to zero, couldn't drag around. Will investigate and log an issue somewhere appropriate. Update – already logged in Gutenberg: https://github.com/WordPress/gutenberg/issues/25814

Also when testing the opacity slider in `Featured Product`, this was tricky to drag out of 100% - need to drag the mouse over the slider line directly. Testing to confirm if this is specific to our block and/or WP 5.6 (etc). Logged a new issue in Gutenberg, this affects cover block: https://github.com/WordPress/gutenberg/issues/27215

**Comment by Aljullu** [comment]
Summary of my testing:
* All Products block: I found three deprecation notices. I opened a separate issue for them: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3475.
* Products by tag: I found a couple of deprecation notices that match the ones of the Hand-picked products block, so I updated the issue description in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3438. I also found a react-dom warning when adding the block, that I logged in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3474.

Functionality-wise, I couldn't spot any issue in any of the two blocks other than some styling glitches in the editor probably caused by the old version of `@woocommerce/components` (#3156).

**Comment by opr** [comment]
- Products by attribute has a couple of deprecation warnings, but otherwise is functioning fine in the editor and front end. Opened an issue for these: #3479
- Reviews by product has a React warning when changing product for the first time in the block's settings #3480
- Reviews by product has a couple of deprecation warnings, but otherwise is functioning fine in the editor and front end. Opened an issue for these: #3481

I did not notice any errors or broken functionality with these blocks.

**Comment by nerrad** [comment]
- **Products By Category** had a couple of deprecation warnings, since they are related to what @opr caught for the Products by attribute block, they can likely just be fixed as a part of #3479 
- Similar to the Reviews by product warning, the **Products by Category** had the same warning so I just included it in #3480 
- The **Newest Products** block had no errors or warnings.

I didn't notice any errors or broken functionality with these blocks (other than known issues like incorrect styled chips).

**Comment by budzanowski** [comment]
- **Reviews by Category**: just deprecation warnings - issue created https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3485
 - **Product Search**: warning when adding the block to the page - issue created https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3486

I have not noticed any broken functionality.

**Comment by senadir** [comment]
**- Filter by price**: deprecation warnings - issue created https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3487
**- Filter by attribute**: no issues
**- Active filters**: no issues

**Comment by nerrad** [comment]
Looks like this issue has been addressed. Thanks everyone for the help in getting things tested 👏
