### ISSUE TITLE
Audit Extensions for Cart and Checkout Block Compatibility

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4129]
This epic groups all issues for extension audits which will focus on testing extension functionality with the Cart and Checkout Blocks.

Audit template:

```
# Extension Audit Template

## Functionality Review

*Install and activate the extension, then going by the documentation, review it's frontend functionality focussing on how it influences products, cart, and the checkout.*

*Write a brief summary of the extension's functionality, *

This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart form
- [ ] My Account Page
- [ ] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

*See how the extension does or does not work when using Product Blocks, Cart Block, and Checkout Block. Does it work as expected? Is functionality that works with the shortcodes broken in the blocks context?*

Issues identified:
- *Summarize any issues you found with the extension*

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| *Location of new integration point, or name of existing integration point.* | *Type e.g. client API, action or filter hook, component, or server side API.* | *Describe what the integration point will be used for.* |  *1*   |
|  |         |
```
