### ISSUE TITLE
Checkout i2: Block Registration System

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4446]
When Inner block areas are available within the Checkout i2 (#4306) we need a system in place where extensions can register blocks for insertion in specific, or all, areas. The merchant can then insert them as needed.

It looks like @senadir has done a little experimentation here already since I see functions named `registerCheckoutBlock`, `getRegisteredBlocks`, and `addToCheckoutArea`. This needs review, but more importantly needs **documentation**, as well as example code and unit tests to confirm it works as needed.

**Tasks**
- [x] Create extensibility interface, or complete existing implementation
- [x] Document extensibility interface
- [x] If not in use by blocks, create tests to confirm extensibility interface is functional

**Comment by mikejolley** [comment]
Marking in progress because work on the `registerCheckoutBlock` system was already started.

**Comment by mikejolley** [comment]
Added tests in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4268/commits/04e339e7b018eabc9108cf40f2e0bb69ccd48fdd

Added docs in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4268/commits/3295ef5a98c36ec0cc2b784eed01767fe2110f9d
