### ISSUE TITLE
Checkout i2: Test extension integration

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4448]
Creating this issue to track progress and serve as a goal for multiple related/blocking issues. This is blocked by #4446, #4306, #4447.

Once the above integration areas/interfaces are available, we need to create a test integration in the form of a Newsletter subscription checkbox. In doing so, we'll need to work on other interfaces and API support for fields.

**Tasks:**
- [x] Successfully register and render a checkbox field on the checkout
- [ ] Add support for validation callbacks (this is not specifically needed for newsletter subscription but we should test that a field could be made required whilst working on this)
- [x] Post the value of the checkbox to the server (via Store API) and ensure an extension can capture and handle this value on the server-side. 
   - [x] Error handling - Can extensions throw a validation error from the server-side?
   - [x] Success handling - Can extensions use the value and/or store it to the order?

I'm increasing the estimate for this based on the assumption work will need to be done on the Store API side as well as client side validation.

**Comment by mikejolley** [comment]
@senadir I think we should start this early on next cycle so we can scope out anything that we're missing, such as API changes.

**Comment by mikejolley** [comment]
I think we can call this done given we've added support at API level and successfully built an integration outside of the repo https://github.com/opr/newsletter-test/blob/main/newsletter-test.php
