### ISSUE TITLE
Checkout i2: Forced Inner Blocks/Required Blocks

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4574]
Spinning this out of #4447

> third-party blocks are a couple of types:
>
> - Optional blocks that merchants can add after enabling the plugin.
> - Required blocks that must be available after enabling the plugin.

We already have a system for registering new optional blocks, and inner block areas for each form step, so the first point is covered.

For _required blocks_ we need a new system so extensions can force insert blocks into the existing checkout layout. Developers decide where the block needs to be inserted, and then it will be locked so it cannot be removed. If it is somehow removed, or missing, the block will be inserted by the system. If an extension is removed, the block needs to be removed by the system.

Todo:

- [x] Add a _force_ attribute to the inner block registration system #4606
- [x] Missing forced blocks must be force inserted by the editor #4606
- [ ] Missing forced blocks must be force inserted on render
- [ ] When an extension is removed, forced/invalid blocks must be removed without causing a block invalidation error
- [x] Template locking should be handled automatically #4606

cc @senadir

**Comment by senadir** [comment]
Some issues that are blocking the requirements above:
- We don't have a system in place to insert into a specific place. We can pass an array in a filter, but how would it handle third party blocks? Sorting arrays with unknown values is hard.
- Removing blocks after a plugin is removed is going to be tricky, our best chance is going to use the template locking hook to remove them on load, but this won't handle persisting.

I'm going to give this a go and see where it takes me.

**Comment by senadir** [comment]
If it proves to be significantly hard to implement frontend forcing via JS. We can look into doing it from PHP via [those filters](https://make.wordpress.org/core/2021/02/18/wordpress-5-7-a-new-dynamic-hook-to-filter-the-content-of-a-single-block/) that @nerrad shared today.

Under the hood, our implementation would hook into those filters and insert the corresponding HTML content to render a block.
