### ISSUE TITLE
Add an e2e test to all blocks to verify they can be added in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4643]
In order to rely more on automatic testing and less on manual smoke testing every time we do a release, we should add a test to all blocks that verifies that the block is available and can be added in the editor. Similar to this one:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/42beb9b1a4166d279f5dff3ec737542b4dfde0ac/tests/e2e/specs/backend/product-search.test.js#L27-L29

In the docs, you can read more about [e2e testing](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/when-to-employ-e2e-testing.md) and learn [how to run our e2e tests](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/javascript-testing.md#how-to-run-end-to-end-tests).

## Status

List of blocks that include a test like this:
* [x] Featured Product Block (#4771)
* [x] Featured Category Block (#4773)
* [x] Hand-picked Products Block (#4788)
* [x] Best Selling Products Block (#4785)
* [x] Top Rated Products Block (#4786)
* [x] Newest Products Block (#4789)
* [x] On Sale Products Block (#4872)
* [x] Products by Category Block (#4872)
* [x] Products by Tag Block (#4872)
* [x] Products by Attribute Block (#4872)
* [x] Product Categories List Block (#4915)
* [x] Reviews by Product (#2808)
* [x] Reviews by Category (#2808)
* [x] All Reviews (#2799)
* [x] Product Search (#2707)
* [x] All Products (#1716)
* [x] Filter Products by Attribute (#4562)
* [x] Filter Products by Price (#4562)
* [x] Filter Products by Stock (#4682)
* [x] Active Product Filters (#4562)
* [x] Cart (#2707)
* [x] Checkout (#2707)
* [x] Mini Cart (#4677)
* [x] Single Product (#1240)
