### ISSUE TITLE
Replace Checkout i1 with Checkout i2

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4681]
Once Checkout i2 is ready and has been tested internally, we'll need to replace the old Checkout Block with the new one. The aim is to have this merged for **Blocks 6.0.0**, end of September.

**Tasks:**

- [x] Replace checkout i1 with i2
- [x] Consolodate styles from i1 into i2, since i2 currently relies on existing styling
- [x] Rename all instances of `checkout-i2` to just `checkout`
- [x] Test migration (automatic) from i1 to i2 on an existing install

**Comment by senadir** [comment]
Should we tackle this before doing a call for testing? We can have it done in a branch that we merge once we do the release.

**Comment by mikejolley** [comment]
@senadir no, lets test it alongside to begin. That also lets us test the migration process using transforms.
