### ISSUE TITLE
Add global styles to all WC Blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4965]
We would like to add [global styles](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) to all WC Blocks.

Below, there is a list of which styles we would like each block to have enabled:

* [x] Featured Category/Featured Product: font size, text color, gradient and duotone (for the overlay), padding, border (color, width, radius). (@gigitux) #5542 #5555 
* [x] Product Categories List: font size, line height, text color, link color. (@gigitux #5133 )
* [ ] ~Product Search: text color, background color (including gradients), border (color and radius -- it should behave as the Search block from Gutenberg), width.~ (on hold, we might rewrite this block soon)
* [x] Active Filters: text color. (@gigitux #5465) 
* [x] Attribute Filter: text color, border (color and radius -- it should be applied to the fields). (@gigitux #5557)
* [x] Price filter: text color, border (color and radius -- it should be applied to the fields). (@gigitux #5559) 
* [x] ~Reviews (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4323): font size, text color.~
* [x] Mini Cart (button): text color (it should also change the icon color). (@gigitux  #5477) 

**Product element blocks**

* [x] Product title: font size, line height, font family, font weight, text transform, text color, background color (including gradients), margin (~#5009~) (@gigitux #5515 )
* [x] Add to cart button: text color, background color (including gradients), padding, border (color and radius) and width
* [x] Category List: font size, text color @gigitux #5516 
* [x] Image: font size, border (radius) @gigitux  #5562
* [x] ~Price: font size, text color~ (on hold: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4965#issuecomment-1005871877)
* [x] Rating: text color (it should change the color of stars) (@gigitux #5521)
* [x] Sale badge: font size, text color, background color (including gradients), padding, color, radius (@gigitux)  #5565
* [x] Stock indicator: font size, text color (@gigitux) #5525
* [x] Summary: font size, text color (@gigitux) #5524
* [x] Tag list: font size, text color, link color (@gigitux) #5528

Some of them are experimental, so you might need Gutenberg installed to get them working.
  
One challenge of this issue is that we might need to update the blocks to use [`apiVersion: 2`](https://make.wordpress.org/core/2020/11/18/block-api-version-2/).

**Comment by Aljullu** [comment]
Heads-up that I'm removing the `good first issue` label given that we found that adding global styles to some of the blocks was more complex than anticipated. We are planning to work on this issue in the future, but as part of a bigger project to properly document all challenges we face with current Gutenberg APIs and the way WC blocks work.

**Comment by gigitux** [comment]
I'm editing the issue description. The `Product Title` block has the global style enabled for the background, so we should enable the global style for the text color too.

**Comment by gigitux** [comment]
The `Product Price` block has a more granular level of customization for font style and text color that we can't reach with global style API. For now, we will not migrate the `Product Price` block to global style.

**Comment by gigitux** [comment]
After an internal discussion, I'm updating the issue description related the `Tag List`block. We will enable global style for link color too.

**Comment by gigitux** [comment]
> The `Product Price` block has a more granular level of customization for font style and text color that we can't reach with global style API. For now, we will not migrate the `Product Price` block to global style.

At the end, we decided to convert the `Product Price` block
