### ISSUE TITLE
Integrate AutomateWoo and MailPoet with Checkout Block

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#5044]
This epic tracks the development of an integration between the Checkout Block, AutomateWoo, and MailPoet.

This currently assumes we're building read-only, non-editable, forced blocks. Estimates will need revising if we add block-level settings to change this.

**Shared**

- [ ] Shared components (newsletter, or checkbox/label combo, like terms and conditions) TBD (3)

**AutomateWoo**

- [x] Build process (5)
- [x] Block creation (2)
- [x] Settings Registration (1)
- [x] Store API Integration (3)

**MailPoet**

- [x] Build process (5)
- [x] Block creation (2)
- [x] Settings Registration (1)
- [x] Store API Integration (3)
