### ISSUE TITLE
Storybook Resurrection

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#5248]
## Project summary

[Storybook](https://storybook.js.org/) is a UI visualization tool that helps documenting our component library, visualizing different variations (called “stories”) and making it easy for developers and designers alike to play around with the component properties and test for unintended changes.

We currently have an implementation of Storybook, but it's mostly bare-bones. The goal of this project is to:

- [x] migrate our current implementation to the latest Storybook best-practices (this makes it easier to add new components with less boilerplate)
- [x] fix the currently available components with the correct controls and relevant stories
- [ ] progressively adding our components and hopefully eventually have full coverage of our library

**Comment by Aljullu** [comment]
@sunyatasattva do you think we can close this epic? I think there is nothing actionable here, right?

**Comment by sunyatasattva** [comment]
@Aljullu Well, yea, the third point on top… I guess was too ambitious for one epic to cover. I kept it open so we could progressively add issues and add coverage to Storybook.
