### ISSUE TITLE
Move `CheckoutStateProvider` into a data store and create a hook to interact with the store

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#6104]
`CheckoutStateProvider` should be moved into a data store and a hook should be created to abstract interaction with it.

There is an existing reducer related to this context provider found in this file https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/5dac3a0e74e2de9c4a4bfecca3f15b380b05433f/assets/js/base/context/providers/cart-checkout/checkout-state/reducer.ts which should be moved into the reducer used by `@wordpress/data`.

### Sub-tasks required to solve this issue
- [ ] Create data store
- [ ] Refactor existing reducer into the one used by the data store above
- [ ] Implement actions and selectors for values that the context previously returned
- [ ] Create a hook that can be used to easily interact with the data store (reducing the need for repeated use of `useSelect` and `useDispatch`)
