### ISSUE TITLE
Product Query: add support to existing filters block

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#6790]
The `Product Query` block has to be compatible with the existing filters block when it is added on post/page and on FSE:
- [x] `Filter Products By Price` block. #7162 
- [x] `Filter Products By Attribute` block. https://github.com/woocommerce/woocommerce-blocks/pull/7186
- [x] `Filter Products By Stock` block. #7251 
- [x] `Filter Products By Rating` block. #7792
- [x] `Active Products Filter` block.

**Comment by gigitux** [comment]
I will close this issue. The PQ supports all the filter blocks
