### ISSUE TITLE
Release process: automatically set milestone date after a successful release

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#6986]
This issue is about automating these steps from the [release process](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/release-initial-checklist.md):

Once the release is successful, automation should perform the following step:

> Edit the GitHub milestone of the release you just shipped and add the current date as the due date (this is used to track ship date as well).

This issue is further divided into following parts:

- [x] [Add new automation to update due date of the milestone after the release.](https://github.com/woocommerce/woocommerce-blocks/issues/7560)
- [x] [Add test cases for the new automation to update the milestone.](https://github.com/woocommerce/woocommerce-blocks/issues/7561)
- [x] [Add documentation for the new automation to update the milestone due date.](https://github.com/woocommerce/woocommerce-blocks/issues/7562)
- [ ] [Update the workflow to include the automation for updating the due date.](https://github.com/woocommerce/woocommerce-blocks/issues/7563)

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
