### ISSUE TITLE
Blockifying Single Product Template

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#8054]
We are looking to blockifying the Single Product Template to empower the merchant to use the features of the Site Editor to create a Single Product Page.

### New Blocks

- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8188
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8186
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8063
- [x] woocommerce/woocommerce-blocks#8233 
- [x] woocommerce/woocommerce-blocks#8479 
- [x] woocommerce/woocommerce-blocks#8465
- [x] woocommerce/woocommerce-blocks#8481
- [x] woocommerce/woocommerce-blocks#8568 
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/9287

### Patterns
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8190
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8191

### Design
- [x]  woocommerce/woocommerce-blocks#9666
- [x] woocommerce/woocommerce-blocks#9659
- [x] woocommerce/woocommerce-blocks#9695
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8453
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8427
- [x] woocommerce/woocommerce-blocks#8630
- [x] woocommerce/woocommerce-blocks#8817 
- [x] woocommerce/woocommerce-blocks#8818 

### Compatibility with extensions
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8204
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8205

### Migration strategy
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8208
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8209

### Investigation about Product Type templates for Single Product views
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8146
 
### Wrapper/No-Wrapper/Template Parts

- [x] Investigate whether a parent block should wrap the blocks woocommerce/woocommerce-blocks#8056
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8314

### Default configuration
- [x] woocommerce/woocommerce-blocks#8480 

### Bugs
- [x] woocommerce/woocommerce-blocks#9662
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8771
- [x] woocommerce/woocommerce-blocks#8528
- [x] woocommerce/woocommerce-blocks#8589 
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8505
- [x] woocommerce/woocommerce-blocks#8629 
- [x] woocommerce/woocommerce-blocks#8701
- [x] woocommerce/woocommerce-blocks#8742 
- [x] woocommerce/woocommerce-blocks#8743
- [x] woocommerce/woocommerce-blocks#8962
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/9000
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8970
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/9030
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/9122
- [x] woocommerce/woocommerce-blocks#9091
- [x] woocommerce/woocommerce-blocks#9270
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/9333
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/9417

### Improvements
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/9686
- [x] https://github.com/WordPress/gutenberg/issues/48964
- [x] https://github.com/WordPress/gutenberg/issues/48963
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/8853
- [x] woocommerce/woocommerce-blocks#9300

### Low Priority
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/5812
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/9402

**Comment by ghost** [comment]
It would be great if custom fields are added in this related.

Similar to this plugin:
https://de.wordpress.org/plugins/woo-custom-product-addons/

**Comment by gigitux** [comment]
All the issues related to this project have been merged in trunk! 🚀
