### ISSUE TITLE
Mini Cart block improvements

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8556]
This is an epic to track all Mini Cart block related issues that we want to look into. At the beginning of the project, there were 25 open issues in WC Blocks + 3 issues in other repos:

These issues need engineering, product or design decisions, so it might be a good idea to surface the feedback request early in the cycle so we aren't blocked:

```[tasklist]
### Need design
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8341
- [ ] https://github.com/woocommerce/woocommerce/issues/42435
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/7359
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/6868
```
```[tasklist]
### Ready to be worked on
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8572
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/7176
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8128
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/7197
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8603
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/6977
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8148
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8302
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/6257
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/6594
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/7016
- [ ] https://github.com/woocommerce/woocommerce/issues/42632
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/7750
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8606
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8787
- [ ] https://github.com/woocommerce/woocommerce/issues/42431
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8814
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8929
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8946
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8965
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9044
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9048
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8716
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8775
- [ ] https://github.com/woocommerce/woocommerce/issues/42645: ideally, I would prefer if Rubik worked on this issue given that it affects C&C extensibility points. We can keep it as a stretch goal in case we finish with everything else.
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/9051
```
```[tasklist]
### Require work on Gutenberg
- [ ] https://github.com/woocommerce/woocommerce/issues/42659
- [ ] https://github.com/woocommerce/woocommerce/issues/42482
```
```[tasklist]
### Require work on WooCommerce
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/6161
```
In theory, we shouldn't need to do anything related to these issues, @Aljullu will review them again before project end date:
```[tasklist]
### Repo cleanup (issues which might have been fixed before the project started)
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/7194
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/7522
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/6874
- [ ] https://github.com/Automattic/wp-calypso/issues/65662
- [ ] https://github.com/Automattic/wp-calypso/issues/66683
- [ ] https://github.com/Automattic/wp-calypso/issues/70204
```

**Comment by Aljullu** [comment]
Superseded by https://github.com/woocommerce/woocommerce-blocks/issues/9198.
