### ISSUE TITLE
Store Editing Patterns

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#8947]
This is an epic to track all issues related to the Store Editing Patterns project

- Designs: [Store Editing Patterns i1 (MVP)](https://woofse.wordpress.com/2023/03/21/store-editing-patterns-i1-mvp/)

```[tasklist]
### Banners, Heros, Promos
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9418
``` 

```[tasklist]
### Header patterns
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9036
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9035
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8953
``` 

```[tasklist]
### Footer patterns
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9055
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9056
```

```[tasklist]
### Featured product patterns
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9041
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9042
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9043
```

```[tasklist]
### Featured category patterns
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9045
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9046
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9101
``` 

```[tasklist]
### Products collection patterns
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8950
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8949
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9104
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9105
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9106
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9107
```

```[tasklist]
### Product details patterns
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9109
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9110
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9111
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9112
```

```[tasklist]
### Testimonials
- [ ] 
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9151
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9152
``` 

```[tasklist]
### ⛔ Don't build for now ⛔
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9141
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9138
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9139
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9140
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9135
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9136
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9137
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8952
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9047
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8951
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9052
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9053
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9054
```
