### ISSUE TITLE
Mini Cart block improvements

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#9198]
This is the continuation of the previous epic: https://github.com/woocommerce/woocommerce-blocks/issues/8556.

```[tasklist]
### Need design
- [ ] https://github.com/woocommerce/woocommerce/issues/42480
- [ ] https://github.com/woocommerce/woocommerce/issues/42435
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/7359
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/6868
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9421
- [ ] https://github.com/woocommerce/woocommerce/issues/42352
```
```[tasklist]
### Ready to be worked on
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9256
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9428
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/9501
- [ ] https://github.com/woocommerce/woocommerce/issues/42632
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9044
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/9329
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9194
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/9196
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8606
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/9487
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9197
- [ ] https://github.com/woocommerce/woocommerce/issues/42431
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8716
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8587
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/9245
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9185
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/9601
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9353
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9557
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9635
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9645
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8775
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9346
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8965
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8823
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9669
- [ ] https://github.com/woocommerce/woocommerce-blocks/pull/9420
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9439
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9584
- [ ] https://github.com/woocommerce/woocommerce/issues/42645: ideally, I would prefer if Rubik worked on this issue given that it affects C&C extensibility points. We can keep it as a stretch goal in case we finish with everything else.
```
```[tasklist]
### Require work on Gutenberg
- [ ] https://github.com/woocommerce/woocommerce/issues/42659
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/8318
- [ ] https://github.com/woocommerce/woocommerce/issues/42369
```
```[tasklist]
### Require work on WooCommerce
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/6161
```

**Comment by Aljullu** [comment]
I'm going to close this issue, as this was a meta-issue that we are not currently working on. All linked issues which are still open will remain open so we can still track them.
