### ISSUE TITLE
Epic: Compatibility audits of Cart and Checkout Block extensions

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9206]
This epic lists all issues regarding the Establish a cohesive extensibility strategy project as defined on pdFofs-X7-p2.

<details>
    <summary>Audit template</summary>

```
# Extension Audit Template

## Functionality Review

*Install and activate the extension, then going by the documentation, review it's frontend functionality focussing on how it influences products, cart, and the checkout.*

*Write a brief summary of the extension's functionality, *

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

*See how the extension does or does not work when using Product Blocks, Cart Block, and Checkout Block. Does it work as expected? Is functionality that works with the shortcodes broken in the blocks context?*

Issues identified:
- *Summarize any issues you found with the extension*

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, (mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| _Location of new integration point, or name of existing integration point._ | _Type e.g. client API, action or filter hook, component, or server side API._ | _Describe what the integration point will be used for._ |  _1_   |
|                                                                             |                                                                               |
```

</details>

```[tasklist]
### Open issues
- [ ] #9218 
- [ ] #9221 
- [ ] #9222 
- [ ] #9231 
``` 

```[tasklist]
### Closed issues
- [ ] #9207
- [ ] #9208
- [ ] #9209 
- [ ] #9210 
- [ ] #9211 
- [ ] #9212 
- [ ] #9213 
- [ ] #9214 
- [ ] #9215 
- [ ] #9216
- [ ] #9217 
- [ ] #9219 
- [ ] #9220 
- [ ] #9224 
- [ ] #9225 
- [ ] #9226 
- [ ] #9227 
- [ ] #9228 
- [ ] #9229 
- [ ] #9230 
- [ ] #9232 
- [ ] #9233 
- [ ] #9223 
- [ ] #9234 
- [ ] #9235 
- [ ] #9236 
- [ ] #9237
```

**Comment by tomxygen** [comment]
Any chance Scalapay support will be included? https://developers.scalapay.com/docs/pluginstall-woocommerce

**Comment by opr** [comment]
Hi there @tomxygen 👋 

Thanks for taking the time to ask about Scalapay and letting us know it isn’t working with the Checkout and Cart blocks. These Blocks are designed to optimize for faster checkout and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently it’s up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

Your best course of action now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

**Comment by message-dimke** [comment]
# Extension Audit Template

## Functionality Review

*Install and activate the extension, then going by the documentation, review it's frontend functionality focussing on how it influences products, cart, and the checkout.*

Sends events to Pinterest (init, page view, add to cart, checkout) so the merchants could see corresponding events under Ads > Conversions tab.

This extension touches: *(mark all that apply)*

- [x] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [x] Add to cart button
- [x] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [x] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [x] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

*See how the extension does or does not work when using Product Blocks, Cart Block, and Checkout Block. Does it work as expected? Is functionality that works with the shortcodes broken in the blocks context?*

Issues identified:
- For Products (Beta), Products by Category and Product by Attribute blocks there is a problem with AddToCart event - it is missing value attribute value (which is a product price).

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, (mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| _Location of new integration point, or name of existing integration point._ | _Type e.g. client API, action or filter hook, component, or server side API._ | _Describe what the integration point will be used for._ |  _1_   |
|                                                                             |                                                                               |

**Comment by nielslange** [comment]
Hello @message-dimke 👋 I noticed that you closed this epic after posting https://github.com/woocommerce/woocommerce-blocks/issues/9206#issuecomment-1559061802. I assume your comment was meant for https://github.com/woocommerce/woocommerce-blocks/issues/9213, wasn't it? I've reopened this epic again for now.

**Comment by message-dimke** [comment]
Omg, @nielslange, thank you for noticing this! I did move the comment to the corresponding issue.

**Comment by nielslange** [comment]
Thanks for moving the issue, @message-dimke. And don't worry about initially posting it here. Things like that happen. 😀

**Comment by ralucaStan** [comment]
Closing this epic issue for now. Great work team!
