### ISSUE TITLE
Epic: Cart/Checkout/Order Received Site Editor Templates

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#9288]
This epic is used for tracking the addition of Cart/Checkout and Order Received Templates.
#9153 and #9165 track overall development across Cart/Checkout and Order Received, respectively.

```[tasklist]
## Cart & Checkout
- [ ] #9153
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9291
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9293
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9295
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9334
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9427
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9706
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9496
```
```[tasklist]
## Order Received
- [ ] #9165
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9292
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9294
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9705
```
```[tasklist]
### Shared
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9863
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9290
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9324
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9289
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9419
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/9865
```
