### ISSUE TITLE
Review the Cart and Checkout blocks tracking usage in WCTracker

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#9571]
**Description:** We use [WCTracker](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-tracker.php#L950-L980) to identify if a store is using the cart and checkout blocks, as well as the shortcodes. We recently discovered that some stores are marked in our data as using the checkout block, but they show a different checkout experience. Some examples:
https://www.wetnwildbeauty.com
https://plantforsoul.ca
https://www.c-rope.de
This should be reviewed to avoid false positives in our data and to develop an accurate view of how many shops use the new experience. 
More context here: p1684772498217239-slack-C11TDJHDZ

**Acceptance criteria:**
- [ ] Investigate if there's something wrong with how we identify if the checkout page includes the checkout block
- [ ] Do the same for the cart page and cart block
- [ ] Review the code the for the cart and checkout shortcodes as well

**Comment by ralucaStan** [comment]
@pmcpinto I've looked at the 3 examples and also looked at 40 other sites; Most of the 40 sites were 🆗, but those which weren't, just like in your 3 examples, had one thing in common: they use another extension for the checkout page. 

It might be that the Checkout Block is included in the page, but the checkout flow is taken over be the extension

**Comment by senadir** [comment]
Raluca is right in that the 3 websites use alternative checkouts, but I don't see any signs of checkout block in the source code, I think this is more likely them not using shortcode as well and one negative assumes the second is positive.

**Comment by senadir** [comment]
I'm still seeing more false positives, I'm unable to reproduce locally. The data suggests that plugins like Elementor and Checkout WC are creating the confusing but I still can't pinpoint it.

I tested Elementor Checkout and will test Checkout WC next.

**Comment by ralucaStan** [comment]
closing this ticket pdFofs-1nw-p2#comment-1799 as we might revisit it in the future.
