### ISSUE TITLE
Migration path from Products to Products Collection block

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#9703]
### Background 

Once the Product Collection block is stable and covers AT LEAST current Products block functionalities, Products block should allow for an easy migration path to Product Collection

### Goal

Provide a migration path, so the users using Products block can easily switch to the Product Collection. One of the options is to make a seamless replacement (considering the functionalities are the same it may be considered an upgrade from one version to another).

In case the latter option is chosen - make sure to preserve the content of the Post Template!

### Requirements:

- update happens automatically when merchant enters the editor
- update happens only for a particular template/page/post that is being edited
- save is still required from merchant to save the changes
- notification is displayed in the Product Collection block about the update (screenshot)
- there's revert button that allows to opt out (screenshot). If dismissed or ignored, it wouldn’t be shown again when the user returns to the editor.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/20098064/5f6fa57d-e1b4-4407-b802-ff021e61dded)

### Additional requirements - may be extracted to separate issues:
- Show "Products (Beta)" block in the inserter only if there's any Products (Beta) block used on the page. That covers the case if the merchant reverted the Product Collection to Products, otherwise it should not be included in the inserter.
```[tasklist]
### Tasks
- [x] Automatic migration from Products to Product Collection
- [x] Display Upgrade Notice
- [x] Allow reverting migration (transform back from Product Collection to Products)
- [x] Add logic to show Upgrade Notice once per store
- [x] Allow for manual upgrade first
```
