### ISSUE TITLE
All Products Block: Add to cart REST API

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#976]
Needed for https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/898

When moving to client side rendering, we need a more robust method of adding items to the cart. We found that the methods that exist in woo core (AJAX endpoints) are not flexible enough since they output notices and generally produce side effects when used directly.

To work around that we need new endpoints and/or an API.

Creation of a new REST API for this was started in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/899 This should be split into a separate PR.

**TODO:**
- [x] Split existing work from #899 into fresh PR
- [x] `cart/add` endpoint
- [x] `cart/delete` endpoint
- [x] Unit tests:
    - [x] Guest vs logged in user
    - [x] Ensure sessions are created
    - [x] Test multiple product types
- ~[ ] Investigate feasibility of local cart and `cart/transfer` endpoint to move from session storage to server.~
