### ISSUE TITLE
Product Collection - End-to-End Testing

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#9783]
This issue covers the necessary development and implementation of End-to-End (E2E) testing for our new block, the "Product Collection"

Each test should validate that the feature is working correctly and efficiently, and should include testing under different conditions and with varying inputs, as applicable.

```[tasklist]
### Tasks
- [x] Block can be added to a page and correctly renders with default settings.
- [x] Sidebar -> Reflects the correct number of columns according to sidebar settings
- [x] Sidebar -> Order By - sort products by title in descending order correctly
- [x] Sidebar -> Products can be filtered based on "on sale" status.
- [x] Sidebar -> Products can be filtered based on selection in handpicked products option
- [x] Sidebar -> Products can be filtered based on keyword.
- [x] Sidebar -> Products can be filtered based on category.
- [ ] [🛑 Blocked] Sidebar -> Products can be filtered based on stock status (in stock, out of stock, or backorder).
- [x] Sidebar -> Products can be filtered based on product attributes like color, size etc.
- [ ] [🛑 Blocked] Sidebar -> Products can be filtered based on product tags.
- [ ] [🛑 Blocked] Sidebar -> Products can be filtered based on authors.
- [x] Responsive -> Block correctly adjusts number of columns on smaller screens
- [x] Toolbar -> Items per page, offset & max page to show
- [x] Inherit query from template
```

**Comment by imanish003** [comment]
I will be writing additional E2E tests for the product collection block. I have already covered a portion of the tests in PR woocommerce/woocommerce-blocks#9825.

**Comment by imanish003** [comment]
I have created a new task woocommerce/woocommerce#42284 for remaining E2E tests, which are currently blocked due to missing fixture data. We will start working on woocommerce/woocommerce#42284 once we complete issue https://github.com/woocommerce/woocommerce/issues/42303.
